Jfoll/automate config api dataset prod 10174
Cosmo-Tech/Babylon pull request #27
Opened 2022-10-13 12:19 UTC by johnfolly

# Dataset Configuration commands

## New requirements

Dataset subgroup require Connector subgroup available or at least one registered connector details

You need to add manually an adt connector details in your deploy configuration file:

```yaml
connector:
  id: #mandatory
  parametersValues:
    AZURE_DIGITAL_TWINS_URL: https://.............api.............digitaltwins.azure.net
    CSM_NUMBER_OF_THREAD: 1
```
## Basic usage

### Create dataset

`babylon api dataset create -n 'Babylon test Dataset'`

This command will create an dataset Object throw Cosmotech API based on generic template on `Babylon/template/working_dir_template/API/Dataset.yaml`

This template does not have an default name value `-n`  option is mandatory

You can use your own template file to create a new dataset, in this case you can set the dataset name directly in the template file `name: org name`; `-n`  option should override the name and the created dataset name with the name specified in `-n` option.

<span style="color:red;font-weight:700;">
    Possible API error when you exeded azure cosmo DB quota, in this case you can delete unused object you created and it should be ok.
</span>

If the new dataset creation completed, `dataset_id` in deploy config file will be set with the id of the created dataset. We can manage this action with `-s` option : default True if false `dataset_id` will not be set.

Notice :  `-s`option automatically override existing `dataset_id` valued in deploy config file.

The optimal use case is creating via template, the only requirement is to set `-n` option

If you are using custom template file, the name must be set at least in your file or in option if not you will receive a clean error log.

### Get All

`babylon api dataset get-all`

Should print all registered dataset

These datasets data can be dump into a json file with the option -o

If your are not or bad authenticated you will receive a clean Unauthorized log

Usage of response filter :
You can use `-f` option to select fields you want in result
`-f key1,key2`  work
`-f 'key1,key2'` work
`-f "key1,key2"` work

As common json filter tools if any of the specified filed are not in the initial result data, you will get an empty response.

### Get

Use Get all first after that copy one dataset id to test

`Babylon api dataset get d-datasetid`

Should print one dataset details

These details can be dump into a json file with the option -o

If your are not or bad authenticated you will receive a clean Unauthorized error log

If any dataset with this id doesn't exist  you will receive a clean Not Found error log

Usage of response filter :
You can use `-f` option to select fields you want in result
`-f key1,key2`  work
`-f 'key1,key2'` work
`-f "key1,key2"` work

As common json filter tools if any of the specified filed are not in the initial result data, you will get an empty response.

### Get Current

`Babylon api dataset get-current`

Do the same things as get but without `dataset_id` argument, the `dataset_id` in deploy config file will be used and is required in deploy config file.

### Delete

Use Get all first after that copy one dataset id to test

`Babylon api dataset delete c-datasetid`

Should unregister a dataset after user confirmation

During dataset id confirmation, if the confirmation id doesn't match you will receive a clean error log

If your are not or bad authenticated you will receive a clean Unauthorized error log

If any dataset with this id doesn't exist  you will receive a clean Not Found error log

2022-10-14 15:00 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/create.py
> +    required=False,
required False is default so maybe you don't need it

2022-10-14 15:01 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/create.py
> +    required=False,
required False is default so maybe you don't need it

2022-10-14 15:02 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/create.py
> +    required=False,
required False is default so maybe you don't need it

2022-10-14 15:03 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/create.py
> +    dataset_name: str,
Optional[str] = None

2022-10-14 15:03 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/create.py
> +    use_working_dir_file: bool = False,
Optional[bool] = False

2022-10-14 15:20 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/delete.py
> +    else:
I think the else is not needed

2022-10-14 15:21 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get.py
> +    required=False,
Required is False by default

2022-10-14 15:22 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get.py
> +    if output_file:
I would put logs from line 85 and 86 here and do a return if not output_file

2022-10-14 15:23 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get_all.py
> +    required=False,
Required false is by default

2022-10-14 15:24 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get_all.py
> +    if output_file:
Log from line 80 here and return if not output file

2022-10-14 15:25 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get_current.py
> +        retrieved_dataset = {"Babylon": "<DRY RUN>"}
I don't think this line is needed

2022-10-14 15:25 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get_current.py
> +    if output_file:
log from 84, 85 here and return if not output file

2022-10-14 15:28 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/update.py
> +    type=str,
type=bool ?

2022-10-14 15:39 UTC, johnfolly commented
> Hi John, I read the code now I have to test the command, I'll do that on monday, have a nice week end !

Hello Emmanuel,

Thanks have a nice week end too.

You can use these bash commands for test

```bash
echo "Babylon"
babylon api dataset get-all
babylon api dataset get-all -f 'id,name'
babylon api dataset get-all -o ../test.json
babylon api dataset get-all -f 'id,name' -o ../test.json
export DAT=$(babylon api dataset create -n test | grep -oh "\w*d-\w*")
echo $DAT
babylon api dataset get $DAT
babylon api dataset update tests/api_files/Dataset.yaml
babylon api dataset get $DAT -f 'id,name'
babylon api dataset get $DAT -o ../test.json
babylon api dataset get $DAT -f 'id,name' -o ../test.json
babylon api dataset get-current
babylon api dataset get-current -f 'id,name'
babylon api dataset get-current -o ../test.json
babylon api dataset get-current -f 'id,name' -o ../test.json
babylon api dataset delete $DAT -f
babylon api dataset get-all -f 'id,name'
echo "Babylon"
babylon api dataset get $DAT
babylon api dataset update tests/api_files/Dataset.yaml
babylon api dataset get $DAT -f 'id,name'
babylon api dataset get $DAT -o ../test.json
babylon api dataset get $DAT -f 'id,name' -o ../test.json
babylon api dataset get-current
babylon api dataset get-current -f 'id,name'
babylon api dataset get-current -o ../test.json
babylon api dataset get-current -f 'id,name' -o ../test.json
babylon api dataset delete $DAT -f
echo "Babylon"
babylon api dataset create
```

2022-10-17 08:49 UTC, o-reo commented
Hi ! I had a doubt so I asked Alexis.
It would be clearer if the connector data was grabbed from a dataset file in the working dir.
And this command should work for a storage connector as well.
Does it make sense to you as well ?

2022-10-18 13:07 UTC, johnfolly commented
> Hi ! I had a doubt so I asked Alexis. It would be clearer if the connector data was grabbed from a dataset file in the working dir. And this command should work for a storage connector if possible. Does it make sense to you as well ?

Hi !

For one platform we deploy only two connectors : one for ADT and one for Azure Storage.
For an chosen Organisation of this platform there are X number of dataset, each of these dataset use one of these twoo connector. It's why we create connectors independently of the dataset.
 
![image](https://user-images.githubusercontent.com/112887402/196437888-74a4f6df-0c7d-4e22-a152-a262d5702ecc.png)

2022-10-18 15:26 UTC, johnfolly commented on Babylon/groups/api/groups/dataset/commands/create.py
> +@argument("dataset_file", type=str, required=False)
I don't use it because babylon can use use_working_dir_file to find a file relative to an setted working dir path

2022-10-18 15:39 UTC, johnfolly commented on Babylon/groups/api/groups/dataset/commands/create.py
> +@argument("dataset_file", type=str, required=False)
It really make sense in case of output file. Thank you !

2022-10-19 07:52 UTC, o-reo requested changes
Minor changes to improve command workflow

2022-10-19 07:52 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/create.py
> +)
Add output file option, see PR #29

2022-10-19 07:52 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/delete.py
> +@argument("dataset_id", type=str, required=True)
Add input file option, see PR #29

2022-10-19 07:52 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get.py
> +@argument("dataset_id", type=str)
Add input file option see  PR #29

2022-10-19 07:52 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get_all.py
> +    type=str,
type click.Path if possible

2022-10-19 07:52 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/get_current.py
> +    type=str,
type click.Path if possible

2022-10-19 14:51 UTC, o-reo reviewed
Just a quick fix to do and it's all good

2022-10-19 14:51 UTC, o-reo commented on Babylon/groups/api/groups/dataset/commands/delete.py
> +@argument("dataset_id", type=str, required=True)
If dataset id is grabbed from the file then dataset_id is not always needed as an argument

2022-10-19 15:29 UTC, o-reo commented
> > Just a quick fix to do and it's all good
> 
> I managed the two cases :
> 
> `babylon api dataset delete d-databaseId`
> 
> and
> 
> `babylon api dataset delete ../dataset.json --from-file`
> 
> Both work it why i kept the arg dataset_id

It seems unusual to me. I would use `babylon api dataset delete -f ../dataset.json`, what do you think ?

2022-10-20 07:55 UTC, johnfolly commented
> > > Just a quick fix to do and it's all good
> > 
> > 
> > I managed the two cases :
> > `babylon api dataset delete d-databaseId`
> > and
> > `babylon api dataset delete ../dataset.json --from-file`
> > Both work it why i kept the arg dataset_id
> 
> It seems unusual to me. I would use `babylon api dataset delete -f ../dataset.json`, what do you think ?

Based on my usage of Babylon I think that for some users It's usual and convenient

2022-10-20 12:31 UTC, o-reo approved these changes
Great, I think you could have used `-f` but anyway. Thanks a bunch :+1:

2022-10-20 15:27 UTC, o-reo commented
I started to rebase your code but there are many conflicts I would prefer for you to manage it because you know better your own code.
```bash
git checkout main
git pull 
git checkout JFOLL/automate_Config_API_dataset_PROD-10174
git rebase -i main
[Ctrl+X]
```
Then go to VS Code and fix merge conflicts
:+1:

2022-10-20 15:38 UTC, johnfolly commented
> I started to rebase your code but there are many conflicts I would prefer for you to manage it because you know better your own code. I am sure I will break something if I do it myself. I am surprised the code has already touched.
> 
> ```shell
> git checkout main
> git pull 
> git checkout JFOLL/automate_Config_API_dataset_PROD-10174
> git rebase -i main
> [Ctrl+X]
> ```
> 
> Then go to VS Code and fix merge conflicts 👍

done ! 

![image](https://user-images.githubusercontent.com/112887402/196994304-40ae5773-554d-41c9-8fc9-f6de11be8226.png)

2022-10-21 08:01 UTC, merged