feat: [PROD-13098] add commands to handle scenario security
Cosmo-Tech/Babylon pull request #282
Opened 2024-02-13 16:56 UTC by esasova

2024-02-14 08:14 UTC, vysahjk commented on Babylon/commands/api/scenarios/security/get.py
> +    response = service.delete(id=identity_id)
service.get instead ?

2024-02-14 08:14 UTC, vysahjk commented on Babylon/commands/api/scenarios/security/add_default.py
> +    response = service.add(details)
service.add_default instead ?

2024-02-14 09:15 UTC, Leopold-Cramer requested changes

2024-02-14 09:15 UTC, Leopold-Cramer commented on Babylon/commands/api/scenarios/security/delete.py
> +        return CommandResponse.fail()
delete endpoints return None

2024-02-14 09:15 UTC, Leopold-Cramer commented on Babylon/commands/api/scenarios/security/add_default.py
> +def add_default(
set_default instead of add default

2024-02-14 09:15 UTC, Leopold-Cramer commented on Babylon/commands/api/scenarios/security/add_default.py
> +    response = service.add(details)
set_default here too

2024-02-14 09:15 UTC, Leopold-Cramer commented on Babylon/commands/api/scenarios/security/service/api.py
> +    def add_default(self, details: dict):
set here too

2024-02-15 07:54 UTC, vysahjk approved these changes
👍🏽

2024-02-15 10:44 UTC, merged