Implement namespace's use command to save context and platfrom values…
Cosmo-Tech/Babylon pull request #283
Opened 2024-02-15 08:10 UTC by mahkoCosmo

… in local

2024-02-15 09:49 UTC, Leopold-Cramer approved these changes

2024-02-15 10:32 UTC, vysahjk requested changes

2024-02-15 10:32 UTC, vysahjk commented on Babylon/utils/environment.py
> +            return None
error log is missing.
What if i run get_all command before `babylon namespace use -c test -p dev` ?

2024-02-15 10:32 UTC, vysahjk commented on Babylon/utils/environment.py
> +        return
return value is missing

2024-02-15 10:32 UTC, vysahjk commented on Babylon/commands/namespace/use.py
> +    logger.info("Namespace set")
1. return value is missing.
2. add logs with context and platform saved

Example:
`kubectl config use-context phoenixAKSdev
> Switched to context "phoenixAKSdev".`

2024-02-16 08:11 UTC, vysahjk approved these changes
👍🏽

2024-02-16 08:11 UTC, merged