feat: upgrade babylon apply logs
Cosmo-Tech/Babylon pull request #340
Opened 2024-03-14 14:43 UTC by Leopold-Cramer

add error report and more info deployed datasets

2024-03-14 15:08 UTC, esasova approved these changes
LGTM :+1:

2024-03-14 15:35 UTC, vysahjk requested changes
top, il me semble ok
il faudra juste check si le error.log exist bien avant de le lire

2024-03-14 15:35 UTC, vysahjk commented on Babylon/commands/macro/apply.py
> +    lines = error_file.readlines()
we need to check if error file exists before

2024-03-15 09:49 UTC, vysahjk approved these changes
ça roule

2024-03-15 10:25 UTC, MohcineTor commented on Babylon/commands/macro/apply.py
> +        if _errors.count > 2:
je crois si mieux ici d'utiliser `if len(_errors) > 2:`

2024-03-15 13:18 UTC, merged