gestion des rapports powerbi
Cosmo-Tech/Babylon pull request #370
Opened 2024-07-09 12:50 UTC by LightWills

2024-07-10 14:06 UTC, LightWills commented
Et ici j'ai mis à jour également le state avec les tags des rapport PowerBI
![Screenshot from 2024-07-10 16-06-43](https://github.com/Cosmo-Tech/Babylon/assets/24258494/93cc071b-3c60-4a11-9128-1eb57eaeaa74)

2024-07-10 14:10 UTC, MohcineTor commented
Hello @LightWills , je valide la logique. On a testé et ça a bien marché, on a bien récupéré les reportId

2024-07-10 14:10 UTC, MohcineTor approved these changes
:+1:

2024-07-10 14:24 UTC, vysahjk commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +            sys.exit(1)
est-il necessaire d'arreter le process ?

2024-07-10 14:25 UTC, vysahjk commented on Babylon/commands/macro/deploy_workspace.py
> +                workspaceCharts = content.get('spec').get('payload').get('webApp').get('options').get('charts')
qu'est-ce qui se passe s'il n'y a de section charts ?

2024-07-10 14:27 UTC, vysahjk commented on Babylon/commands/macro/deploy_workspace.py
> +                                    filter(lambda x: x.get('reportTag') is not None and x.get('reportTag') == rtag,
qu'est-ce qui se passe si il n'y a pas de reportTag ou il est mal écrite ?

2024-07-10 14:52 UTC, LightWills commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +            sys.exit(1)
non c'est pas nécessaire, je peux corriger ce point

2024-07-10 14:56 UTC, LightWills commented on Babylon/commands/macro/deploy_workspace.py
> +                                    filter(lambda x: x.get('reportTag') is not None and x.get('reportTag') == rtag,
dans ce cas le reportId pas mis à jours ( car le reportTab est **abscent ou mal ecrit** ). Il n'aura pas d'alarme et le process ne s'arretera pas. 

J'ai testé ce point ici : et on remarquera qu'il na pas de reportId ( parce que dans le workspace.yaml le reportTab est **abscent ou mal ecrit** )

- organisation id : o-p5xdodz7lo7j0
- workspace id : w-ejoke85eyx737


![Screenshot from 2024-07-10 16-55-38](https://github.com/Cosmo-Tech/Babylon/assets/24258494/4eec237d-7953-4073-bd7d-faa1d6a63941)

2024-07-11 07:06 UTC, LightWills commented on Babylon/commands/macro/deploy_workspace.py
> +                workspaceCharts = content.get('spec').get('payload').get('webApp').get('options').get('charts')
c'est un cas que j'ai pas gérer, je suis partir du fait qu'on dispose tjr de charts dans le fichier workspace.yaml afin de lancer correctement les runTemplates

hier j'ai mis a jour le code pour prendre en compte cette eventualité. Si on as pas de charts, on l'aura pas non plus dans le payload de l'api.

2024-07-11 07:56 UTC, vysahjk commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +        response = oauth_request(
il faut gérer le workspaceId, sinon la request ne va pas aboutir.

2024-07-11 07:58 UTC, vysahjk commented on Babylon/commands/macro/deploy_workspace.py
> +                if (content.get('spec').get('payload').get('webApp').get('options').get('charts') is not None):
tu peux utiliser les valeurs par default s'il te plaît.

2024-07-11 07:59 UTC, vysahjk commented on Babylon/commands/macro/deploy_workspace.py
> +        if (workspaceCharts is not None):
tu peux améliorer la syntax s'il te plaît

2024-07-11 08:01 UTC, vysahjk requested changes
quelques choses à modifier encore.

2024-07-11 12:51 UTC, LightWills commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +        response = oauth_request(
c'est fait

2024-07-11 12:51 UTC, LightWills commented on Babylon/commands/macro/deploy_workspace.py
> +        if (workspaceCharts is not None):
c'est fait

2024-07-11 13:15 UTC, vysahjk approved these changes

2024-07-11 13:18 UTC, merged