fix power bi errors
Cosmo-Tech/Babylon pull request #379
Opened 2024-07-23 14:51 UTC by LightWills

2024-07-24 08:44 UTC, MohcineTor commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +        jsonPayload = json.loads(self.spec["payload"])
Ici comme déjà dit nibaldo t'a utilisé `camel case` par contre dans tout le code babylon utilise `snake_case`

2024-07-24 08:44 UTC, MohcineTor commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +            if self.state["powerbi"]['dashboard_view'] is not None:
Ici, Tu as testé le premier déploiement dans lequel `dashboard_view dans state == ' '`
```
  powerbi:
    dashboard_view: ''
    group_id: ''
    scenario_view: ''
```

2024-07-24 12:30 UTC, LightWills commented
j'ai testé les fonctionnalités implémentées dans cette PR pour le cas ou pour un premier deploiement on a des rapports powerbi et que pour un second deploiment les rapports powe bi sont commentés.

Le deploiement s'effectue correctement avec les reportIds qui sont bien présents dans les dashboardViews et scenarioViews

Deployments: 

   * Organization   : o-9rwrlxx80zq5
   * Solution       : sol-wr2rq52vjgk9
   * Workspace      : w-kvrvpkj4jgnp

![Screenshot from 2024-07-24 14-29-35](https://github.com/user-attachments/assets/4df73500-accb-4f30-b00a-6d908a8b8f3a)

2024-07-24 12:48 UTC, LightWills commented
Parreillement quand on comment la section webapp dans le workspace.yaml, on a plus d'erreur lors du deploiement

Deployments: 

   * Organization   : o-04owzkxkr37q
   * Solution       : sol-pjoedkox757x
   * Workspace      : w-end86je3pld3

![image](https://github.com/user-attachments/assets/9483187f-042b-4ccc-bb90-fab1a6c48960)

2024-07-24 12:59 UTC, MohcineTor reviewed
t'a pris en considération d'utilisé `snake_case` ou lieu de  `camel case `

2024-07-24 15:21 UTC, MohcineTor commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +                for dashboard_view_tag in self.state["powerbi"]['dashboard_view']:
Une question : que va-t-il se passer lors du premier déploiement dans lequel les tags ne sont pas présents dans le state ?
car dans le 1ᵉʳ déploiement le state coté power --> dashoard_view et vide après ce déploiement en replier le state par des tags des reports id?

2024-07-24 15:21 UTC, MohcineTor commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +                for scenario_view_tag in self.state["powerbi"]['scenario_view']:
Le même chose ici pour les scenario_view ?

2024-07-24 16:34 UTC, LightWills commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +                for dashboard_view_tag in self.state["powerbi"]['dashboard_view']:
Pour le premier deploiement le state->powerbi->dashoard_view est egale à : { } si et seulement si **on pas de reportTag dans la section powerbi**

- Si on a des reportTags dans la section powerbi ils sont save dans le state et le state est utilisé pour faire une mise a jour du payload afin de bien remonter les reportsId 
- Si on a pas des reportTags dans la section powerbi, rien ne se passe et le payload ne sera pas modifier avant l'update du workspace => **il n'aura pas d'injection du reportId dans les dashboardViews et scenarioView**

2024-07-24 16:34 UTC, LightWills commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +                for scenario_view_tag in self.state["powerbi"]['scenario_view']:
@MohcineTor cf ma reponse plus haut

2024-07-25 07:55 UTC, vysahjk commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +        jsonPayload = json.loads(self.spec["payload"])
je ne vois pas la passage à snake_case

2024-07-25 07:55 UTC, vysahjk commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +            if self.state["powerbi"]['dashboard_view'] is not None:
la réponse ?

2024-07-25 08:01 UTC, vysahjk commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +        jsonPayload = json.loads(self.spec["payload"])
il y des considérations que Mohcine a remonter.

2024-07-25 08:01 UTC, vysahjk requested changes
il y a des considérations que Mohcine a remonter.

2024-07-25 12:22 UTC, LightWills commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
> +            if self.state["powerbi"]['dashboard_view'] is not None:
oui jai testé, si dans le premier deploiement les variables du state sont vides alors dans les deploiements suivants on ne pourra pas injectés les **reportId** dans le payload du workspace car les valeur de state->dashboard_view et de state->scenario_view sont vides

2024-07-25 12:26 UTC, LightWills commented
@MohcineTor ta remarque a été prise en compte

2024-07-25 12:36 UTC, MohcineTor commented on Babylon/commands/azure/staticwebapp/services/swa_api_svc.py
> +            logger.error(f"[webapp] Failed to launch of webapp {webapp_name} in resource group {resource_group_name}")
C'est plutôt mieux ici :
`logger.error(f"[webapp] Failed to create  webapp {webapp_name} in resource group {resource_group_name}")`

2024-07-25 12:48 UTC, MohcineTor commented on Babylon/commands/powerbi/dataset/services/powerbi_api_svc.py
> +            logger.error(f"[powerbi] failed to update dataset with dataset_id : {dataset_id}")
`logger.error(f"[powerbi] failed to  update credentials on dataset_id : {dataset_id}")`

2024-07-25 12:51 UTC, MohcineTor commented on Babylon/commands/powerbi/workspace/services/powerb__worskapce_users_svc.py
> +            logger.error("[powerbi] failed to add identifier")
`logger.error(f"[powerbi] failed to add identifier {identifier} ")`

2024-07-25 12:52 UTC, MohcineTor commented on Babylon/commands/powerbi/workspace/services/powerb__worskapce_users_svc.py
> +            logger.error("[powerbi] failed to delete identifier")
`logger.error(f"[powerbi] failed to delete identifier {identifier} ")`

2024-07-25 12:54 UTC, MohcineTor commented on Babylon/utils/checkers.py
> +    logger.error("@_!#$%^&*()<>?/|}{~:. characters are forbidden")
`logger.error("@_!#$%^&*()<>?/|}{~:\\. characters are forbidden")`

2024-07-25 12:57 UTC, MohcineTor commented on Babylon/commands/api/workspaces/services/workspaces_api_svc.py
>          return response
`logger.error('An error occurred while sending a workspace secret key')`

2024-07-25 14:31 UTC, MohcineTor approved these changes
C'est okey de mon côté :+1:

2024-07-25 14:40 UTC, MohcineTor requested changes
hello @LightWills une autre truc, c'est coté webapp même t'a mis en commentaire la partie webapp dans `warkspace.yaml`, je vois et toujours présente dans le worksapce.yaml quand je récupère with swagger ?
[response_1721918743692.json](https://github.com/user-attachments/files/16379500/response_1721918743692.json)

Découpe, j'ai testé de mon côté, voici les cas d'utilisation :

-   1 Cas dans lequel on fait le premier déploiement avec le fichier workspace.yaml : la partie webapp est en commentaire. On lance un déploiement, ça marche. Une fois que je récupère le workspace depuis Swagger, je vois bien que webapp est null.
![image](https://github.com/user-attachments/assets/1e408c98-2b23-447e-accc-f9c19e9108f4)
![image](https://github.com/user-attachments/assets/5178f57c-7a54-447f-baca-f48db5ddb9fe)
-    2 Cas dans lequel on laisse la partie webapp dans le fichier workspace.yaml : je récupère encore une fois le workspace depuis Swagger, je vois la présence de webapp.
![image](https://github.com/user-attachments/assets/546f4eae-9656-4273-80e5-78aebea93c53)
![image](https://github.com/user-attachments/assets/5b125868-d556-4745-839e-2950d83c4044)
-    3  Maintenant, c'est l'utilisateur, mais encore une fois avec webapp en commentaire : on relance le déploiement et on voit que webapp est toujours présent. Il ne prend pas en considération le commentaire de la partie webapp dans le fichier workspace.yaml.
![image](https://github.com/user-attachments/assets/44042d0b-f527-4367-ab35-3146f8c8cf62)

2024-07-26 09:32 UTC, merged