Automate azure resource template deployment
Cosmo-Tech/Babylon pull request #61
Opened 2022-11-16 10:28 UTC by johnfolly

# Automate azure resource template deployment 

## Usage: `babylon azure arm [OPTIONS] COMMAND [ARGS]`

  Group interacting with Azure Resources Manager

  Requires key `azure_subscription` in the platform config file.

## Options:
  `-h`, `--help`  Show help message and exit.

## Commands:

  `create`  Apply a resource deployment config via arm deployment.
  `delete`  Delete a resource deployment via arm deployment.
  `list`    List all the deployments for a resource group.
  `run`     Apply a resource deployment config via arm deployment.

2022-11-21 15:24 UTC, o-reo reviewed
:+1:

2022-11-21 15:24 UTC, o-reo commented on Babylon/groups/azure/groups/arm/commands/delete.py
> +
You should use `utils.interactive.confirm_deletion`

2022-11-21 15:24 UTC, o-reo commented on Babylon/groups/azure/groups/arm/commands/delete.py
> +    return poller.status()
You may rebase to main and use the new `CommandResponse` class !
See  `azure acr get-all` for an example

2022-11-21 15:24 UTC, o-reo commented on Babylon/groups/azure/groups/arm/commands/run.py
> +    return poller.status()
`CommandResponse`

2022-11-23 09:06 UTC, o-reo requested changes
There are some missing CommandResponse. 
This branch is commiting changes that are already merge, there is something wrong with the way it has been rebased.

2022-11-23 09:06 UTC, o-reo commented on Babylon/utils/configuration.py
>  import os
You are committing something that has already been pushed.
Rebase was not done correctly.

2022-11-23 09:06 UTC, o-reo commented on Babylon/utils/response.py
> +from typing import Any
Rebase was not done correctly

2022-11-23 09:06 UTC, o-reo commented on Babylon/utils/working_dir.py
>  import pathlib
Rebase was not done correctly

2022-11-23 09:47 UTC, johnfolly commented
@o-reo you can do a final review now

2022-11-23 15:05 UTC, o-reo commented on Babylon/groups/azure/groups/arm/commands/create.py
> +    return CommandResponse(data=f"Resource deployment config created, content was dumped in {deployment_name}.yaml")
```suggestion
    return CommandResponse(data=arm_deployment)
```
Data must be a `dict`

2022-11-23 15:42 UTC, o-reo approved these changes

2022-11-24 08:18 UTC, merged